services:
  bookify.api:
    image: bookify.api
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #      - ASPNETCORE_HTTP_PORTS=7000
    #      - ASPNETCORE_HTTPS_PORTS=7001
    ports:
      - "7000:7000"
      - "7001:7001"

  bookify-db:
    image: postgres:17.2
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"