services:
  bookify-db:
    image: postgres:17.2
    container_name: bookify-db
    environment:
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  bookify-api:
    image: bookify-api
    container_name: bookify-api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
    ports:
      - "7000:7000"
      - "7001:7001"
  
  bookify-idp:
    image: quay.io/keycloak/keycloak:26.0
    container_name: bookify-idp
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - identitydata:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - "18080:8080"
  
  bookify-seq:
    image: datalust/seq:2024.3
    container_name: bookify-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
  
  bookify-redis:
    image: redis:7.4.1
    container_name: bookify-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
  identitydata: